name: Build

on:
  push:
    branches:
      - '!main'
  pull_request: { }

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - path: golang
            version: 1.20.2
          - path: node
            version: 18.10.0-buster
          - path: postgres
            version: 14
          - path: debian
            version: 12.1
          - path: ubuntu
            version: 20.04
          - path: buildkite-agent
            version: 3.40.0-ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          file: images/${{ matrix.path }}/${{ matrix.version }}/Dockerfile
          context: images/${{ matrix.path }}/${{ matrix.version }}
          tags: containers.monetr.dev/${{ matrix.path }}:${{ matrix.version }}
