name: Build

on:
  push:
    branches:
      - main

jobs:
  docker:
    environment: containers.monetr.dev
    name: Docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - path: golang
            version: 1.20.2
          - path: node
            version: 18.10.0-buster
          - path: postgres
            version: 14
          - path: debian
            version: 12.1
          - path: ubuntu
            version: 20.04
          - path: buildkite-agent
            version: 3.40.0-ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate Tag
        id: tag
        run: |
          echo ::set-output name=POST_TAG::$(git describe --tag | cut -d "-" -f 2,3)
      - name: Build and push ghcr.io
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: images/${{ matrix.path }}/${{ matrix.version }}/Dockerfile
          path: images/${{ matrix.path }}/${{ matrix.version }}
          tags: latest,${{ matrix.version}},${{ matrix.version }}-${{ steps.tag.outputs.POST_TAG }}
          repository: monetr/build-containers/${{ matrix.path }}
